package com.ezone.devops.pipeline.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum GlobalVariableType {

    SYS_COMPANY_NAME("SYS_COMPANY_NAME"),
    SYS_BUILD_REPO("SYS_BUILD_REPO"),
    SYS_BUILD_BRANCH("SYS_BUILD_BRANCH"),
    SYS_BUILD_TAG("SYS_BUILD_TAG"),
    SYS_BUILD_COMMIT("SYS_BUILD_COMMIT"),
    SYS_BUILD_COMMIT_TIMESTAMP("SYS_BUILD_COMMIT_TIMESTAMP"),
    SYS_BUILD_SNAPSHOT_VERSION("SYS_BUILD_SNAPSHOT_VERSION"),
    SYS_BUILD_RELEASE_VERSION("SYS_BUILD_RELEASE_VERSION"),
    SYS_PIPELINE_ID("SYS_PIPELINE_ID"),
    SYS_LAST_RELEASE_VERSION("SYS_LAST_RELEASE_VERSION"),
    SYS_PIPELINE_NAME("SYS_PIPELINE_NAME"),
    SYS_PIPELINE_BUILD_NUMBER("SYS_PIPELINE_BUILD_NUMBER"),
    SYS_PIPELINE_BUILD_ID("SYS_PIPELINE_BUILD_ID"),
    SYS_TRIGGER_USER("SYS_TRIGGER_USER"),
    SYS_BUILD_YEAR("SYS_BUILD_YEAR"),
    SYS_BUILD_MONTH("SYS_BUILD_MONTH"),
    SYS_BUILD_DAY("SYS_BUILD_DAY"),
    SYS_BUILD_DATE("SYS_BUILD_DATE");

    @Getter
    private String key;
}